name: pyfesom-docs
channels:
  - conda-forge
dependencies:
  - python=2.7
  - netcdf4=1.2.9
  - sphinx=1.4.1
  - pandas=0.19.2
  - scipy=0.19.0
  - numpydoc=0.7.0
  - joblib=0.11
  - sphinx=1.5
  - seawater
